/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.customer.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Customer service. Represents a row in the &quot;ACS_Customer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.customer.model.impl.CustomerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.customer.model.impl.CustomerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Customer
 * @generated
 */
@ProviderType
public interface CustomerModel extends BaseModel<Customer> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a customer model instance should use the {@link Customer} interface instead.
	 */

	/**
	 * Returns the primary key of this customer.
	 *
	 * @return the primary key of this customer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this customer.
	 *
	 * @param primaryKey the primary key of this customer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this customer.
	 *
	 * @return the uuid of this customer
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this customer.
	 *
	 * @param uuid the uuid of this customer
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the customer ID of this customer.
	 *
	 * @return the customer ID of this customer
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this customer.
	 *
	 * @param customerId the customer ID of this customer
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the customer name of this customer.
	 *
	 * @return the customer name of this customer
	 */
	@AutoEscape
	public String getCustomerName();

	/**
	 * Sets the customer name of this customer.
	 *
	 * @param customerName the customer name of this customer
	 */
	public void setCustomerName(String customerName);

	/**
	 * Returns the customer email of this customer.
	 *
	 * @return the customer email of this customer
	 */
	@AutoEscape
	public String getCustomerEmail();

	/**
	 * Sets the customer email of this customer.
	 *
	 * @param customerEmail the customer email of this customer
	 */
	public void setCustomerEmail(String customerEmail);

	/**
	 * Returns the customer address of this customer.
	 *
	 * @return the customer address of this customer
	 */
	@AutoEscape
	public String getCustomerAddress();

	/**
	 * Sets the customer address of this customer.
	 *
	 * @param customerAddress the customer address of this customer
	 */
	public void setCustomerAddress(String customerAddress);

	/**
	 * Returns the customer contact of this customer.
	 *
	 * @return the customer contact of this customer
	 */
	@AutoEscape
	public String getCustomerContact();

	/**
	 * Sets the customer contact of this customer.
	 *
	 * @param customerContact the customer contact of this customer
	 */
	public void setCustomerContact(String customerContact);

	/**
	 * Returns the customer nric of this customer.
	 *
	 * @return the customer nric of this customer
	 */
	@AutoEscape
	public String getCustomerNRIC();

	/**
	 * Sets the customer nric of this customer.
	 *
	 * @param customerNRIC the customer nric of this customer
	 */
	public void setCustomerNRIC(String customerNRIC);

	/**
	 * Returns the aaa_start_date of this customer.
	 *
	 * @return the aaa_start_date of this customer
	 */
	public Date getAaa_start_date();

	/**
	 * Sets the aaa_start_date of this customer.
	 *
	 * @param aaa_start_date the aaa_start_date of this customer
	 */
	public void setAaa_start_date(Date aaa_start_date);

	/**
	 * Returns the aaa_group ID of this customer.
	 *
	 * @return the aaa_group ID of this customer
	 */
	public long getAaa_groupId();

	/**
	 * Sets the aaa_group ID of this customer.
	 *
	 * @param aaa_groupId the aaa_group ID of this customer
	 */
	public void setAaa_groupId(long aaa_groupId);

	/**
	 * Returns the aaa_company ID of this customer.
	 *
	 * @return the aaa_company ID of this customer
	 */
	public long getAaa_companyId();

	/**
	 * Sets the aaa_company ID of this customer.
	 *
	 * @param aaa_companyId the aaa_company ID of this customer
	 */
	public void setAaa_companyId(long aaa_companyId);

	/**
	 * Returns the aaa_user ID of this customer.
	 *
	 * @return the aaa_user ID of this customer
	 */
	public long getAaa_userId();

	/**
	 * Sets the aaa_user ID of this customer.
	 *
	 * @param aaa_userId the aaa_user ID of this customer
	 */
	public void setAaa_userId(long aaa_userId);

	/**
	 * Returns the aaa_user name of this customer.
	 *
	 * @return the aaa_user name of this customer
	 */
	@AutoEscape
	public String getAaa_userName();

	/**
	 * Sets the aaa_user name of this customer.
	 *
	 * @param aaa_userName the aaa_user name of this customer
	 */
	public void setAaa_userName(String aaa_userName);

	/**
	 * Returns the aaa_create date of this customer.
	 *
	 * @return the aaa_create date of this customer
	 */
	public Date getAaa_createDate();

	/**
	 * Sets the aaa_create date of this customer.
	 *
	 * @param aaa_createDate the aaa_create date of this customer
	 */
	public void setAaa_createDate(Date aaa_createDate);

	/**
	 * Returns the aaa_modified date of this customer.
	 *
	 * @return the aaa_modified date of this customer
	 */
	public Date getAaa_modifiedDate();

	/**
	 * Sets the aaa_modified date of this customer.
	 *
	 * @param aaa_modifiedDate the aaa_modified date of this customer
	 */
	public void setAaa_modifiedDate(Date aaa_modifiedDate);

	/**
	 * Returns the service name of this customer.
	 *
	 * @return the service name of this customer
	 */
	@AutoEscape
	public String getServiceName();

	/**
	 * Sets the service name of this customer.
	 *
	 * @param serviceName the service name of this customer
	 */
	public void setServiceName(String serviceName);

	@Override
	public Customer cloneWithOriginalValues();

}